#!/usr/bin/env python3
"""
Generate a thin STL model of an ArUco 4x4 marker — black cells only.

Usage:
    python generate_marker_model.py --id 0 --size 50 --height 1.0
    python generate_marker_model.py --id 7 --size 30 --height 0.5 -o marker7.stl
"""

import argparse
import struct
import sys


# ---------------------------------------------------------------------------
# Marker grid
# ---------------------------------------------------------------------------

def get_marker_grid(marker_id: int, dict_name: str):
    """Return a 6×6 list-of-lists (1 = black, 0 = white) via OpenCV."""
    try:
        import cv2
    except ImportError:
        sys.exit(
            "Error: OpenCV is required.\n"
            "Install it with:  pip install opencv-python"
        )

    dict_map = {
        "4x4_50":   cv2.aruco.DICT_4X4_50,
        "4x4_100":  cv2.aruco.DICT_4X4_100,
        "4x4_250":  cv2.aruco.DICT_4X4_250,
        "4x4_1000": cv2.aruco.DICT_4X4_1000,
    }
    if dict_name not in dict_map:
        sys.exit(f"Error: unknown dictionary '{dict_name}'. "
                 f"Choose from: {', '.join(dict_map)}")

    aruco_dict = cv2.aruco.getPredefinedDictionary(dict_map[dict_name])

    # Render at 20 px per cell → 120×120 image; sample cell centres
    cell_px   = 20
    n_cells   = 6           # 4×4 data + 1-cell border on every side
    img_size  = cell_px * n_cells

    img = cv2.aruco.generateImageMarker(aruco_dict, marker_id, img_size)

    grid = []
    for r in range(n_cells):
        row = []
        for c in range(n_cells):
            px = int((c + 0.5) * cell_px)
            py = int((r + 0.5) * cell_px)
            row.append(1 if img[py, px] < 128 else 0)   # 0 px value → black
        grid.append(row)
    return grid


# ---------------------------------------------------------------------------
# STL geometry helpers
# ---------------------------------------------------------------------------

def _tri(normal, v1, v2, v3):
    return (normal, v1, v2, v3)


def box_triangles(x0, y0, z0, x1, y1, z1):
    """12 outward-facing triangles for an axis-aligned box."""
    tris = []

    # Bottom  (z = z0, normal -Z)
    tris.append(_tri((0, 0, -1), (x0, y0, z0), (x1, y1, z0), (x1, y0, z0)))
    tris.append(_tri((0, 0, -1), (x0, y0, z0), (x0, y1, z0), (x1, y1, z0)))

    # Top     (z = z1, normal +Z)
    tris.append(_tri((0, 0,  1), (x0, y0, z1), (x1, y0, z1), (x1, y1, z1)))
    tris.append(_tri((0, 0,  1), (x0, y0, z1), (x1, y1, z1), (x0, y1, z1)))

    # Front   (y = y0, normal -Y)
    tris.append(_tri((0, -1, 0), (x0, y0, z0), (x1, y0, z0), (x1, y0, z1)))
    tris.append(_tri((0, -1, 0), (x0, y0, z0), (x1, y0, z1), (x0, y0, z1)))

    # Back    (y = y1, normal +Y)
    tris.append(_tri((0,  1, 0), (x1, y1, z0), (x0, y1, z0), (x0, y1, z1)))
    tris.append(_tri((0,  1, 0), (x1, y1, z0), (x0, y1, z1), (x1, y1, z1)))

    # Left    (x = x0, normal -X)
    tris.append(_tri((-1, 0, 0), (x0, y0, z0), (x0, y0, z1), (x0, y1, z1)))
    tris.append(_tri((-1, 0, 0), (x0, y0, z0), (x0, y1, z1), (x0, y1, z0)))

    # Right   (x = x1, normal +X)
    tris.append(_tri((1,  0, 0), (x1, y0, z0), (x1, y1, z1), (x1, y0, z1)))
    tris.append(_tri((1,  0, 0), (x1, y0, z0), (x1, y1, z0), (x1, y1, z1)))

    return tris


# ---------------------------------------------------------------------------
# Terminal visualisation
# ---------------------------------------------------------------------------

# Each cell is rendered as 2 wide characters so cells look square in a terminal.
_BLACK = "\033[40m  \033[0m"   # black background
_WHITE = "\033[107m  \033[0m"  # bright-white background


def print_marker(grid, marker_id: int, dict_name: str):
    n = len(grid)
    border = _BLACK * (n + 2)   # one extra cell padding on each side
    sep    = "\n"

    lines = [border]
    for row in grid:
        line = _BLACK
        for cell in row:
            line += _BLACK if cell else _WHITE
        line += _BLACK
        lines.append(line)
    lines.append(border)

    print(sep.join(lines))
    print(f"  dict={dict_name}  id={marker_id}")


# ---------------------------------------------------------------------------
# STL writer
# ---------------------------------------------------------------------------

def write_binary_stl(path: str, triangles: list):
    """Write a list of (normal, v1, v2, v3) tuples as a binary STL file."""
    header = b"ArUco marker - generated by generate_marker_model.py"
    header = header[:80].ljust(80, b"\x00")

    with open(path, "wb") as f:
        f.write(header)
        f.write(struct.pack("<I", len(triangles)))
        for normal, v1, v2, v3 in triangles:
            f.write(struct.pack("<3f", *normal))
            f.write(struct.pack("<3f", *v1))
            f.write(struct.pack("<3f", *v2))
            f.write(struct.pack("<3f", *v3))
            f.write(struct.pack("<H", 0))   # attribute byte count


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate a thin STL of an ArUco 4×4 marker (black cells only).",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--id",     type=int,   default=0,         metavar="ID",
                        help="Marker ID")
    parser.add_argument("--size",   type=float, default=65.0,      metavar="MM",
                        help="Total marker size in mm")
    parser.add_argument("--height", type=float, default=1.0,       metavar="MM",
                        help="Extrusion height (thickness) in mm")
    parser.add_argument("--dict",   type=str,   default="4x4_50",
                        choices=["4x4_50", "4x4_100", "4x4_250", "4x4_1000"],
                        help="ArUco dictionary to use")
    parser.add_argument("--mirror", action="store_true",
                        help="Mirror the marker horizontally (for printing on the reverse side)")
    parser.add_argument("-o", "--output", type=str, default=None,  metavar="FILE",
                        help="Output STL filename (default: marker_<id>.stl)")

    args = parser.parse_args()

    max_ids = {"4x4_50": 49, "4x4_100": 99, "4x4_250": 249, "4x4_1000": 999}
    if args.id < 0 or args.id > max_ids[args.dict]:
        sys.exit(f"Error: marker ID must be 0–{max_ids[args.dict]} for dict '{args.dict}'")
    if args.size <= 0:
        sys.exit("Error: --size must be positive")
    if args.height <= 0:
        sys.exit("Error: --height must be positive")

    output = args.output or f"marker_{args.id}.stl"

    grid = get_marker_grid(args.id, args.dict)
    if args.mirror:
        grid = [row[::-1] for row in grid]
    print_marker(grid, args.id, args.dict)
    print()
    n_cells   = len(grid)          # 6
    cell_mm   = args.size / n_cells

    triangles = []
    black_count = 0
    for r in range(n_cells):
        for c in range(n_cells):
            if grid[r][c] == 1:
                x0 = c * cell_mm
                x1 = x0 + cell_mm
                # Flip rows so the marker reads correctly (+Y = up in STL)
                y0 = (n_cells - r - 1) * cell_mm
                y1 = y0 + cell_mm
                triangles.extend(box_triangles(x0, y0, 0.0, x1, y1, args.height))
                black_count += 1

    write_binary_stl(output, triangles)

    if args.mirror:
        print("  (mirrored)")
    print(f"Wrote '{output}'")
    print(f"  Dictionary : {args.dict}  |  ID : {args.id}")
    print(f"  Size       : {args.size} × {args.size} mm  |  Height : {args.height} mm")
    print(f"  Cell size  : {cell_mm:.4f} mm")
    print(f"  Black cells: {black_count} / {n_cells * n_cells}  "
          f"({black_count * 12} triangles)")


if __name__ == "__main__":
    main()
